version: "3.9"


services:
  react:
    build: /home/nurzhan/Desktop/Go/Go_project/
    container_name: react
    ports:
      - "3000:3000"
    volumes:
      - /home/nurzhan/Desktop/Go/Go_project
    depends_on:
      - go


  postgres-db:
    build: ./postgres-db
    container_name: db
    ports:
      - 5436:5432
    volumes:
      -  /home/nurzhan/Desktop/Go/Go_Backend/Go_project/postgres-db/pgdata/pgdata/
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata
    networks:
      - backend

  django:
    build: /home/nurzhan/Desktop/Go/Django_Backend/settings
    container_name: django
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/home/nurzhan/Desktop/Go/Django_Backend/settings/
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    networks:
      - backend
      
  go:
    build: ./
    container_name: go
    command: bash -c "go run ./cmd/main.go -b 0.0.0.0:8080"
    ports:
      - "8080:8080"
    volumes:
      - .:/home/nurzhan/Desktop/Go/Go_Backend/Go_project/cmd/
    depends_on:
      - postgres-db
    networks:
      - backend
networks:
  backend:
    driver: bridge
