# Generated by Django 3.2 on 2023-03-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
