# Generated by Django 4.1.3 on 2023-02-14 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='ip',
            field=models.CharField(default=1, max_length=15, verbose_name='IP address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='star',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='furni.ratingsstar', verbose_name='star'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
