# Generated by Django 4.1.3 on 2023-02-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0002_comments_ip_comments_star_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='star',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, max_length=2, verbose_name='star'),
        ),
        migrations.DeleteModel(
            name='RatingsStar',
        ),
    ]
