# Generated by Django 4.1.6 on 2023-02-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0002_alter_customuser_phone_alter_seller_mobilenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='CategoryID',
            new_name='categoryID',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ImageNo1',
            new_name='imageNo1',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ImageNo2',
            new_name='imageNo2',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ImageNo3',
            new_name='imageNo3',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ImageNo4',
            new_name='imageNo4',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ImageNo5',
            new_name='imageNo5',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='PDdesc',
            new_name='pddesc',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ProductTitle',
            new_name='productTitle',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='SellerID',
            new_name='sellerID',
        ),
    ]
