# Generated by Django 4.1.6 on 2023-02-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0003_rename_categoryid_products_categoryid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='productTitle',
            new_name='producttitle',
        ),
    ]
