# Generated by Django 4.1.3 on 2023-02-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0003_alter_comments_star_delete_ratingsstar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='star',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
