# Generated by Django 3.2 on 2023-03-01 13:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0004_alter_comments_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='CardNo',
            field=models.CharField(max_length=19, null=True, validators=[django.core.validators.RegexValidator(message="Card number must be entered in the format: '**** **** **** ****'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,14}$')]),
        ),
        migrations.CreateModel(
            name='TokenUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
