# Generated by Django 4.0.3 on 2023-02-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0004_rename_producttitle_products_producttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='Rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
