# Generated by Django 3.2 on 2023-03-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0005_auto_20230301_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenUser',
        ),
    ]
