# Generated by Django 4.0.3 on 2023-02-06 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0005_comments_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='furni.comments'),
        ),
    ]
