# Generated by Django 4.0.3 on 2023-02-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0006_products_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='rating',
            new_name='Rating',
        ),
    ]
