# Generated by Django 4.0.3 on 2023-02-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0007_rename_rating_products_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Rating',
        ),
    ]
