# Generated by Django 4.0.3 on 2023-02-08 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0008_rename_rating_comments_rating_remove_products_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='producttitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='furni.products'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
