# Generated by Django 4.0.3 on 2023-02-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0010_alter_comments_producttitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='producttitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='furni.products'),
        ),
    ]
