# Generated by Django 4.0.3 on 2023-02-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0011_alter_comments_producttitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
