# Generated by Django 4.0.3 on 2023-02-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0012_alter_comments_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Value:')),
            ],
            options={
                'verbose_name': 'Star of rating',
                'verbose_name_plural': 'Star of rating',
                'ordering': ['-value'],
            },
        ),
        migrations.RemoveField(
            model_name='comments',
            name='rating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP address')),
                ('producttitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='furni.products')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furni.ratingstar', verbose_name='star')),
            ],
        ),
    ]
