# Generated by Django 4.0.3 on 2023-02-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0013_ratingstar_remove_comments_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingstar',
            name='value',
            field=models.SmallIntegerField(),
        ),
    ]
