# Generated by Django 4.0.3 on 2023-02-08 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0014_alter_ratingstar_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='producttitle',
        ),
        migrations.AddField(
            model_name='rating',
            name='ProductID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='furni.products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ratingstar',
            name='value',
            field=models.SmallIntegerField(default=0, verbose_name='Value:'),
        ),
    ]
