# Generated by Django 4.0.3 on 2023-02-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0015_remove_rating_producttitle_rating_productid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='ProductID',
            new_name='Product',
        ),
    ]
