# Generated by Django 4.0.3 on 2023-02-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0016_rename_productid_rating_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='Product',
            new_name='ProductID',
        ),
    ]
