# Generated by Django 4.0.3 on 2023-02-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0017_rename_product_rating_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='iaa',
            field=models.CharField(default=1, max_length=15, verbose_name='IP address'),
            preserve_default=False,
        ),
    ]
