# Generated by Django 4.1.3 on 2023-02-08 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0020_alter_rating_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='imageNo1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='imageNo2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='imageNo3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='imageNo4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='imageNo5',
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='img')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='furni.products')),
            ],
        ),
    ]
