# Generated by Django 4.1.3 on 2023-02-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0023_remove_products_image_alter_productimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
