# Generated by Django 4.1.3 on 2023-02-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0024_alter_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='furni.category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sellerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='furni.seller'),
        ),
    ]
