export const CREATE_USER = 'CREATE_USER'
export const RECIEVED_NEW_USER = 'RECIEVED_NEW_USER'
export const FAILURE_CREATE_USER = 'FAILURE_CREATE_USER'


export const LOGIN_USER = 'LOGIN_USER'
export const SUCCESSFUL_LOGIN_USER = 'SUCCESSFUL_LOGIN_USER '
export const FAILURE_LOGIN_USER = 'FAILURE_LOGIN_USE'