export const CREATE_USER = 'CREATE_USER'
export const RECIEVED_NEW_USER = 'RECIEVED_NEW_USER'
export const FAILURE_CREATE_USER = 'FAILURE_CREATE_USER'


export const LOGIN_USER = 'LOGIN_USER'
export const SUCCESSFUL_LOGIN_USER = 'SUCCESSFUL_LOGIN_USER '
export const FAILURE_LOGIN_USER = 'FAILURE_LOGIN_USER'


export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS'
export const SUCCESS_SEARCH_PRODUCTS = 'SUCCESS_SEARCH_PRODUCTS'
export const FAILURE_SEARCH_PRODUCTS = 'FAILURE_SEARCH_PRODUCTS'


export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'
export const SUCCESS_FILTER_PRODUCTS = 'SUCCESS_FILTER_PRODUCTS'
export const FAILURE_FILTER_PRODUCTS = 'FAILURE_FILTER_PRODUCTS'

export const CREATE_COMMENT = 'CREATE_COMMENT'
export const RECIEVED_NEW_COMMENT = 'RECIEVED_NEW_COMMENT'
export const FAILURE_CREATE_COMMENT= 'FAILURE_CREATE_COMMENT'


export const GET_COMMENT = 'GET_COMMENT'
export const SUCCESS_GET_COMMENT = 'SUCCESS_GET_COMMENT'
export const FAILURE_GET_COMMENT = 'FAILURE_GET_COMMENT'

export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const SUCCESS_CREATE_PRODUCT = 'SUCCESS_CREATE_PRODUCT'
export const FAILURE_CREATE_PRODUCT = 'FAILURE_CREATE_PRODUCT'